// <auto-generated />
using System;
using HAMS.TeachingTimetable.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HAMS.TeachingTimetable.Migrations
{
    [DbContext(typeof(TeachingTimetableDbContext))]
    [Migration("20260804100436_InitialTeachingTimetable")]
    partial class InitialTeachingTimetable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("teaching")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HAMS.TeachingTimetable.Domain.AssignmentRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AssignmentRoles", "teaching");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0013-000000000001"),
                            Code = "ORDINARY",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Ordinary"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0013-000000000002"),
                            Code = "SUBSTITUTE",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Substitute"
                        });
                });

            modelBuilder.Entity("HAMS.TeachingTimetable.Domain.ClassTeacherAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid>("StaffPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StaffPersonId", "EffectiveFrom", "EffectiveTo");

                    b.HasIndex("ClassId", "AcademicYearId", "EffectiveFrom", "EffectiveTo");

                    b.ToTable("ClassTeacherAssignments", "teaching");
                });

            modelBuilder.Entity("HAMS.TeachingTimetable.Domain.LeadingTeacherAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid>("StaffPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StaffPersonId", "EffectiveFrom", "EffectiveTo");

                    b.HasIndex("SubjectId", "AcademicYearId", "EffectiveFrom", "EffectiveTo");

                    b.ToTable("LeadingTeacherAssignments", "teaching");
                });

            modelBuilder.Entity("HAMS.TeachingTimetable.Domain.Period", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Code")
                        .IsUnique();

                    b.ToTable("Periods", "teaching");
                });

            modelBuilder.Entity("HAMS.TeachingTimetable.Domain.SubjectTeachingAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignmentRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid>("StaffPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentRoleId");

                    b.HasIndex("StaffPersonId", "EffectiveFrom", "EffectiveTo");

                    b.HasIndex("SubjectId", "ClassId", "AcademicYearId", "EffectiveFrom", "EffectiveTo");

                    b.ToTable("SubjectTeachingAssignments", "teaching");
                });

            modelBuilder.Entity("HAMS.TeachingTimetable.Domain.SubstitutionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GeneratedAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OriginalAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SubstituteStaffPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("SubstitutionDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAssignmentId")
                        .IsUnique();

                    b.HasIndex("OriginalAssignmentId");

                    b.ToTable("SubstitutionRecords", "teaching");
                });

            modelBuilder.Entity("HAMS.TeachingTimetable.Domain.TimetableEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeachingAssignmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId");

                    b.HasIndex("TeachingAssignmentId");

                    b.HasIndex("ClassId", "AcademicYearId", "DayOfWeek", "PeriodId")
                        .IsUnique();

                    b.ToTable("TimetableEntries", "teaching");
                });

            modelBuilder.Entity("HAMS.TeachingTimetable.Domain.SubjectTeachingAssignment", b =>
                {
                    b.HasOne("HAMS.TeachingTimetable.Domain.AssignmentRole", null)
                        .WithMany()
                        .HasForeignKey("AssignmentRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.TeachingTimetable.Domain.SubstitutionRecord", b =>
                {
                    b.HasOne("HAMS.TeachingTimetable.Domain.SubjectTeachingAssignment", null)
                        .WithMany()
                        .HasForeignKey("GeneratedAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.TeachingTimetable.Domain.SubjectTeachingAssignment", null)
                        .WithMany()
                        .HasForeignKey("OriginalAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.TeachingTimetable.Domain.TimetableEntry", b =>
                {
                    b.HasOne("HAMS.TeachingTimetable.Domain.Period", null)
                        .WithMany()
                        .HasForeignKey("PeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.TeachingTimetable.Domain.SubjectTeachingAssignment", null)
                        .WithMany()
                        .HasForeignKey("TeachingAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
