<Project>

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Company>Hirilandhoo School</Company>
    <Product>Hirilandhoo Academic Management System (HAMS)</Product>
    <NeutralLanguage>en</NeutralLanguage>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
