// <auto-generated />
using System;
using HAMS.Intervention.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HAMS.Intervention.Migrations
{
    [DbContext(typeof(InterventionDbContext))]
    partial class InterventionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("intervention")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HAMS.Intervention.Domain.BehaviourCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPositive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("BehaviourCategories", "intervention");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0026-000000000001"),
                            Code = "MERIT",
                            DisplayOrder = 1,
                            IsActive = true,
                            IsPositive = true,
                            Name = "Merit"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0026-000000000002"),
                            Code = "RECOGNITION",
                            DisplayOrder = 2,
                            IsActive = true,
                            IsPositive = true,
                            Name = "Recognition"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0026-000000000003"),
                            Code = "DISRUPTION",
                            DisplayOrder = 3,
                            IsActive = true,
                            IsPositive = false,
                            Name = "Disruption"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0026-000000000004"),
                            Code = "DISRESPECT",
                            DisplayOrder = 4,
                            IsActive = true,
                            IsPositive = false,
                            Name = "Disrespect"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0026-000000000005"),
                            Code = "BULLYING",
                            DisplayOrder = 5,
                            IsActive = true,
                            IsPositive = false,
                            Name = "Bullying"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0026-000000000006"),
                            Code = "OTHER",
                            DisplayOrder = 6,
                            IsActive = true,
                            IsPositive = false,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("HAMS.Intervention.Domain.BehaviourIncident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionTaken")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("BehaviourCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConfidentialityTierCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateOnly>("OccurredDate")
                        .HasColumnType("date");

                    b.Property<Guid>("RecordedByPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("ReviewedByPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("StudentPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BehaviourCategoryId");

                    b.HasIndex("StudentPersonId", "OccurredDate");

                    b.ToTable("BehaviourIncidents", "intervention");
                });

            modelBuilder.Entity("HAMS.Intervention.Domain.CarriedForwardGap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("IdentifiedDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("InterventionCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<Guid>("LearningOutcomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TopicClosureId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InterventionCaseId");

                    b.HasIndex("TopicClosureId");

                    b.HasIndex("StudentPersonId", "LearningOutcomeId");

                    b.ToTable("CarriedForwardGaps", "intervention");
                });

            modelBuilder.Entity("HAMS.Intervention.Domain.InterventionCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CarriedForwardGapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("ClosedDate")
                        .HasColumnType("date");

                    b.Property<string>("ConfidentialityTierCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("InterventionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LearningOutcomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OpenedByPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("OpenedDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("StudentPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TriggeringKeyStageEvaluationId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InterventionTypeId");

                    b.HasIndex("StudentPersonId", "SubjectId", "Status");

                    b.ToTable("InterventionCases", "intervention");
                });

            modelBuilder.Entity("HAMS.Intervention.Domain.InterventionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignedStaffPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("InterventionCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("InterventionCaseId");

                    b.ToTable("InterventionPlans", "intervention");
                });

            modelBuilder.Entity("HAMS.Intervention.Domain.InterventionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("InterventionTypes", "intervention");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0024-000000000001"),
                            Code = "ADDITIONAL_PRACTICE",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Additional Practice"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0024-000000000002"),
                            Code = "ONE_ON_ONE_SUPPORT",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "One-on-One Support"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0024-000000000003"),
                            Code = "PEER_TUTORING",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Peer Tutoring"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0024-000000000004"),
                            Code = "PARENT_CONFERENCE",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Parent Conference"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0024-000000000005"),
                            Code = "LEARNING_SUPPORT_REFERRAL",
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "Learning Support Referral"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0024-000000000006"),
                            Code = "OTHER",
                            DisplayOrder = 6,
                            IsActive = true,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("HAMS.Intervention.Domain.ReassessmentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InterventionCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KeyStageEvaluationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RecordedByPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InterventionCaseId");

                    b.ToTable("ReassessmentAttempts", "intervention");
                });

            modelBuilder.Entity("HAMS.Intervention.Domain.TopicClosure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RequestedByPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("ReviewedByPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TeachingTopicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TeachingTopicId", "CreatedAtUtc");

                    b.ToTable("TopicClosures", "intervention");
                });

            modelBuilder.Entity("HAMS.Intervention.Domain.BehaviourIncident", b =>
                {
                    b.HasOne("HAMS.Intervention.Domain.BehaviourCategory", null)
                        .WithMany()
                        .HasForeignKey("BehaviourCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.Intervention.Domain.CarriedForwardGap", b =>
                {
                    b.HasOne("HAMS.Intervention.Domain.InterventionCase", null)
                        .WithMany()
                        .HasForeignKey("InterventionCaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HAMS.Intervention.Domain.TopicClosure", null)
                        .WithMany()
                        .HasForeignKey("TopicClosureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.Intervention.Domain.InterventionCase", b =>
                {
                    b.HasOne("HAMS.Intervention.Domain.InterventionType", null)
                        .WithMany()
                        .HasForeignKey("InterventionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.Intervention.Domain.InterventionPlan", b =>
                {
                    b.HasOne("HAMS.Intervention.Domain.InterventionCase", null)
                        .WithMany()
                        .HasForeignKey("InterventionCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.Intervention.Domain.ReassessmentAttempt", b =>
                {
                    b.HasOne("HAMS.Intervention.Domain.InterventionCase", null)
                        .WithMany()
                        .HasForeignKey("InterventionCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
