// <auto-generated />
using System;
using HAMS.AssessmentEvaluation.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HAMS.AssessmentEvaluation.Migrations
{
    [DbContext(typeof(AssessmentEvaluationDbContext))]
    [Migration("20260805032904_InitialAssessmentEvaluation")]
    partial class InitialAssessmentEvaluation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("assessment")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HAMS.AssessmentEvaluation.Domain.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssessmentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<Guid?>("ExternalExaminationBoardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalSyllabusCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MaxMarks")
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentCategoryId");

                    b.HasIndex("ExternalExaminationBoardId");

                    b.HasIndex("SubjectId", "GradeId", "TermId");

                    b.ToTable("Assessments", "assessment");
                });

            modelBuilder.Entity("HAMS.AssessmentEvaluation.Domain.AssessmentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AssessmentCategories", "assessment");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0020-000000000001"),
                            Code = "TERM_EXAM",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Term Exam"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0020-000000000002"),
                            Code = "CONTINUOUS_ASSESSMENT",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Continuous Assessment"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0020-000000000003"),
                            Code = "QUIZ",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Quiz"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0020-000000000004"),
                            Code = "PROJECT",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Project"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0020-000000000005"),
                            Code = "OTHER",
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("HAMS.AssessmentEvaluation.Domain.AssessmentResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AdjustedMark")
                        .HasColumnType("decimal(6,2)");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("FinalMark")
                        .HasColumnType("decimal(6,2)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<Guid>("KeyStagePolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ModeratedMark")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("ModerationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("RawMark")
                        .HasColumnType("decimal(6,2)");

                    b.Property<Guid>("RecordedByPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SpecialResultStateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("StudentPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SupersededById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecialResultStateId");

                    b.HasIndex("AssessmentId", "StudentPersonId", "IsCurrent");

                    b.ToTable("AssessmentResults", "assessment");
                });

            modelBuilder.Entity("HAMS.AssessmentEvaluation.Domain.AssessmentScheme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AssessmentSchemes", "assessment");
                });

            modelBuilder.Entity("HAMS.AssessmentEvaluation.Domain.AssessmentSchemeComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssessmentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssessmentSchemeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("WeightPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentCategoryId");

                    b.HasIndex("AssessmentSchemeId", "AssessmentCategoryId")
                        .IsUnique();

                    b.ToTable("AssessmentSchemeComponents", "assessment");
                });

            modelBuilder.Entity("HAMS.AssessmentEvaluation.Domain.ExternalExaminationBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ExternalExaminationBoards", "assessment");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0021-000000000001"),
                            Code = "CAMBRIDGE",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Cambridge Assessment International Education"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0021-000000000002"),
                            Code = "EDEXCEL",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Pearson Edexcel"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0021-000000000003"),
                            Code = "SSC",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Secondary School Certificate (SSC)"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0021-000000000004"),
                            Code = "HSC",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Higher Secondary Certificate (HSC)"
                        });
                });

            modelBuilder.Entity("HAMS.AssessmentEvaluation.Domain.GradeBand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("GradeScaleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MinPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradeScaleId", "Code")
                        .IsUnique();

                    b.ToTable("GradeBands", "assessment");
                });

            modelBuilder.Entity("HAMS.AssessmentEvaluation.Domain.GradeScale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("GradeScales", "assessment");
                });

            modelBuilder.Entity("HAMS.AssessmentEvaluation.Domain.SpecialResultState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SpecialResultStates", "assessment");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0022-000000000001"),
                            Code = "MEDICAL_CERTIFICATE_EXCUSED",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Medical Certificate Excused"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0022-000000000002"),
                            Code = "AUTHORIZED_TRAVEL_MAKEUP",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Authorized Travel - Make-Up Exam"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0022-000000000003"),
                            Code = "CALIBRATION_ONLY",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Calibration Only"
                        });
                });

            modelBuilder.Entity("HAMS.AssessmentEvaluation.Domain.Assessment", b =>
                {
                    b.HasOne("HAMS.AssessmentEvaluation.Domain.AssessmentCategory", null)
                        .WithMany()
                        .HasForeignKey("AssessmentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.AssessmentEvaluation.Domain.ExternalExaminationBoard", null)
                        .WithMany()
                        .HasForeignKey("ExternalExaminationBoardId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HAMS.AssessmentEvaluation.Domain.AssessmentResult", b =>
                {
                    b.HasOne("HAMS.AssessmentEvaluation.Domain.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.AssessmentEvaluation.Domain.SpecialResultState", null)
                        .WithMany()
                        .HasForeignKey("SpecialResultStateId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HAMS.AssessmentEvaluation.Domain.AssessmentSchemeComponent", b =>
                {
                    b.HasOne("HAMS.AssessmentEvaluation.Domain.AssessmentCategory", null)
                        .WithMany()
                        .HasForeignKey("AssessmentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.AssessmentEvaluation.Domain.AssessmentScheme", null)
                        .WithMany()
                        .HasForeignKey("AssessmentSchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.AssessmentEvaluation.Domain.GradeBand", b =>
                {
                    b.HasOne("HAMS.AssessmentEvaluation.Domain.GradeScale", null)
                        .WithMany()
                        .HasForeignKey("GradeScaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
