// <auto-generated />
using System;
using HAMS.OrgCurriculum.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HAMS.OrgCurriculum.Migrations
{
    [DbContext(typeof(OrgDbContext))]
    [Migration("20260805092022_PromotionAndNextGrade")]
    partial class PromotionAndNextGrade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("org")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.AcademicYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Code")
                        .IsUnique();

                    b.ToTable("AcademicYears", "org");
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.Campus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Code")
                        .IsUnique();

                    b.ToTable("Campuses", "org");
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CampusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CampusId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("AcademicYearId", "Code")
                        .IsUnique();

                    b.ToTable("Classes", "org");
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.ClassGrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("ClassId", "GradeId")
                        .IsUnique();

                    b.ToTable("ClassGrades", "org");
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.CurriculumFramework", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CurriculumFrameworks", "org");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0004-000000000001"),
                            Code = "NCF",
                            Description = "Maldives National Curriculum Framework.",
                            IsActive = true,
                            Name = "National Curriculum Framework"
                        });
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.DeliveryMode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DeliveryModes", "org");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000001"),
                            Code = "TIMETABLED",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Timetabled"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0006-000000000002"),
                            Code = "INTEGRATED",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Integrated"
                        });
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.EvaluationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("EvaluationModels", "org");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000001"),
                            Code = "MASTERY",
                            Description = "Continuous learning-outcome mastery only.",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Mastery"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000002"),
                            Code = "ASSESSMENT",
                            Description = "External syndicated summative examination only.",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Assessment"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0003-000000000003"),
                            Code = "HYBRID",
                            Description = "Continuous assessment combined with a time-boxed exam.",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Hybrid"
                        });
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("NextGradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NextGradeId");

                    b.HasIndex("SchoolId", "Code")
                        .IsUnique();

                    b.ToTable("Grades", "org");
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.GradeKeyStageAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KeyStageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("KeyStageId");

                    b.HasIndex("GradeId", "AcademicYearId", "EffectiveFrom", "EffectiveTo");

                    b.ToTable("GradeKeyStageAssignments", "org");
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.Holiday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("HolidayTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameDv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HolidayTypeId");

                    b.HasIndex("SchoolId", "Date")
                        .IsUnique();

                    b.ToTable("Holidays", "org");
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.HolidayType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("HolidayTypes", "org");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0014-000000000001"),
                            Code = "PUBLIC_HOLIDAY",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Public Holiday"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0014-000000000002"),
                            Code = "RELIGIOUS_HOLIDAY",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Religious Holiday"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0014-000000000003"),
                            Code = "SCHOOL_DECLARED",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "School-Declared Holiday"
                        });
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.Indicator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("LearningOutcomeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LearningOutcomeId", "Code")
                        .IsUnique();

                    b.ToTable("Indicators", "org");
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.KeyStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PhaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.HasIndex("SchoolId", "Code")
                        .IsUnique();

                    b.ToTable("KeyStages", "org");
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.KeyStagePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AchievementScaleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssessmentSchemeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvaluationModelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GradeScaleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<Guid>("KeyStageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PromotionPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("SupersededById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("EvaluationModelId");

                    b.HasIndex("KeyStageId", "AcademicYearId", "IsCurrent");

                    b.ToTable("KeyStagePolicies", "org");
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.LearningArea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CurriculumFrameworkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CurriculumFrameworkId");

                    b.ToTable("LearningAreas", "org");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000001"),
                            Code = "ISLAM_SPIRITUALITY",
                            CurriculumFrameworkId = new Guid("00000000-0000-0000-0004-000000000001"),
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Islam & Spirituality"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000002"),
                            Code = "LANGUAGE_COMMUNICATION",
                            CurriculumFrameworkId = new Guid("00000000-0000-0000-0004-000000000001"),
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Language & Communication"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000003"),
                            Code = "MATHEMATICS",
                            CurriculumFrameworkId = new Guid("00000000-0000-0000-0004-000000000001"),
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000004"),
                            Code = "ENVIRONMENT_SCIENCE_TECHNOLOGY",
                            CurriculumFrameworkId = new Guid("00000000-0000-0000-0004-000000000001"),
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Environment/Science & Technology"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000005"),
                            Code = "HEALTH_WELLBEING",
                            CurriculumFrameworkId = new Guid("00000000-0000-0000-0004-000000000001"),
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "Health & Wellbeing"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000006"),
                            Code = "SOCIAL_SCIENCES",
                            CurriculumFrameworkId = new Guid("00000000-0000-0000-0004-000000000001"),
                            DisplayOrder = 6,
                            IsActive = true,
                            Name = "Social Sciences"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000007"),
                            Code = "CREATIVE_ARTS",
                            CurriculumFrameworkId = new Guid("00000000-0000-0000-0004-000000000001"),
                            DisplayOrder = 7,
                            IsActive = true,
                            Name = "Creative Arts"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0005-000000000008"),
                            Code = "ENTREPRENEURSHIP",
                            CurriculumFrameworkId = new Guid("00000000-0000-0000-0004-000000000001"),
                            DisplayOrder = 8,
                            IsActive = true,
                            Name = "Entrepreneurship"
                        });
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.LearningOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("SubStrandId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubStrandId", "Code")
                        .IsUnique();

                    b.ToTable("LearningOutcomes", "org");
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.LearningOutcomePrerequisite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LearningOutcomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PrerequisiteLearningOutcomeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PrerequisiteLearningOutcomeId");

                    b.HasIndex("LearningOutcomeId", "PrerequisiteLearningOutcomeId")
                        .IsUnique();

                    b.ToTable("LearningOutcomePrerequisites", "org");
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.MediumOfInstruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("MediumsOfInstruction", "org");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0007-000000000001"),
                            Code = "DHIVEHI",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Dhivehi"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0007-000000000002"),
                            Code = "ENGLISH",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "English"
                        });
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.Phase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Code")
                        .IsUnique();

                    b.ToTable("Phases", "org");
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Schools", "org");
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.Strand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SyllabusId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SyllabusId", "Code")
                        .IsUnique();

                    b.ToTable("Strands", "org");
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.SubStrand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("StrandId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StrandId", "Code")
                        .IsUnique();

                    b.ToTable("SubStrands", "org");
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("DefaultMediumOfInstructionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeliveryModeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("LearningAreaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DefaultMediumOfInstructionId");

                    b.HasIndex("DeliveryModeId");

                    b.HasIndex("LearningAreaId");

                    b.HasIndex("SchoolId", "Code")
                        .IsUnique();

                    b.ToTable("Subjects", "org");
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.Syllabus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SupersededById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "IsCurrent");

                    b.ToTable("Syllabuses", "org");
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.SyllabusGradeApplicability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SyllabusId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("SyllabusId", "GradeId")
                        .IsUnique();

                    b.ToTable("SyllabusGradeApplicabilities", "org");
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId", "Code")
                        .IsUnique();

                    b.ToTable("Terms", "org");
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.WorkingDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("WorkingDays", "org");
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.AcademicYear", b =>
                {
                    b.HasOne("HAMS.OrgCurriculum.Domain.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.Campus", b =>
                {
                    b.HasOne("HAMS.OrgCurriculum.Domain.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.Class", b =>
                {
                    b.HasOne("HAMS.OrgCurriculum.Domain.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.OrgCurriculum.Domain.Campus", null)
                        .WithMany()
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HAMS.OrgCurriculum.Domain.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.ClassGrade", b =>
                {
                    b.HasOne("HAMS.OrgCurriculum.Domain.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HAMS.OrgCurriculum.Domain.Grade", null)
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.Grade", b =>
                {
                    b.HasOne("HAMS.OrgCurriculum.Domain.Grade", null)
                        .WithMany()
                        .HasForeignKey("NextGradeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HAMS.OrgCurriculum.Domain.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.GradeKeyStageAssignment", b =>
                {
                    b.HasOne("HAMS.OrgCurriculum.Domain.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.OrgCurriculum.Domain.Grade", null)
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.OrgCurriculum.Domain.KeyStage", null)
                        .WithMany()
                        .HasForeignKey("KeyStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.Holiday", b =>
                {
                    b.HasOne("HAMS.OrgCurriculum.Domain.HolidayType", null)
                        .WithMany()
                        .HasForeignKey("HolidayTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.OrgCurriculum.Domain.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.Indicator", b =>
                {
                    b.HasOne("HAMS.OrgCurriculum.Domain.LearningOutcome", null)
                        .WithMany()
                        .HasForeignKey("LearningOutcomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.KeyStage", b =>
                {
                    b.HasOne("HAMS.OrgCurriculum.Domain.Phase", null)
                        .WithMany()
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.OrgCurriculum.Domain.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.KeyStagePolicy", b =>
                {
                    b.HasOne("HAMS.OrgCurriculum.Domain.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.OrgCurriculum.Domain.EvaluationModel", null)
                        .WithMany()
                        .HasForeignKey("EvaluationModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.OrgCurriculum.Domain.KeyStage", null)
                        .WithMany()
                        .HasForeignKey("KeyStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.LearningArea", b =>
                {
                    b.HasOne("HAMS.OrgCurriculum.Domain.CurriculumFramework", null)
                        .WithMany()
                        .HasForeignKey("CurriculumFrameworkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.LearningOutcome", b =>
                {
                    b.HasOne("HAMS.OrgCurriculum.Domain.SubStrand", null)
                        .WithMany()
                        .HasForeignKey("SubStrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.LearningOutcomePrerequisite", b =>
                {
                    b.HasOne("HAMS.OrgCurriculum.Domain.LearningOutcome", null)
                        .WithMany()
                        .HasForeignKey("LearningOutcomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.OrgCurriculum.Domain.LearningOutcome", null)
                        .WithMany()
                        .HasForeignKey("PrerequisiteLearningOutcomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.Phase", b =>
                {
                    b.HasOne("HAMS.OrgCurriculum.Domain.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.Strand", b =>
                {
                    b.HasOne("HAMS.OrgCurriculum.Domain.Syllabus", null)
                        .WithMany()
                        .HasForeignKey("SyllabusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.SubStrand", b =>
                {
                    b.HasOne("HAMS.OrgCurriculum.Domain.Strand", null)
                        .WithMany()
                        .HasForeignKey("StrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.Subject", b =>
                {
                    b.HasOne("HAMS.OrgCurriculum.Domain.MediumOfInstruction", null)
                        .WithMany()
                        .HasForeignKey("DefaultMediumOfInstructionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.OrgCurriculum.Domain.DeliveryMode", null)
                        .WithMany()
                        .HasForeignKey("DeliveryModeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.OrgCurriculum.Domain.LearningArea", null)
                        .WithMany()
                        .HasForeignKey("LearningAreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.OrgCurriculum.Domain.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.Syllabus", b =>
                {
                    b.HasOne("HAMS.OrgCurriculum.Domain.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.SyllabusGradeApplicability", b =>
                {
                    b.HasOne("HAMS.OrgCurriculum.Domain.Grade", null)
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.OrgCurriculum.Domain.Syllabus", null)
                        .WithMany()
                        .HasForeignKey("SyllabusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.Term", b =>
                {
                    b.HasOne("HAMS.OrgCurriculum.Domain.AcademicYear", null)
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.OrgCurriculum.Domain.WorkingDay", b =>
                {
                    b.HasOne("HAMS.OrgCurriculum.Domain.School", null)
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
