namespace HAMS.TeachingTimetable.Domain;

/// <summary>
/// Configurable lookup (build plan §1.6 explicitly names "AssignmentRole"), not an enum.
/// Distinguishes how a <see cref="SubjectTeachingAssignment"/> row came to exist — an ordinary
/// assignment vs. one generated by a <see cref="SubstitutionRecord"/> — from the Platform.Access
/// <c>Role</c> it grants, which is always the same (Subject Teacher) either way: "substitute
/// access uses exactly the same permission code as ordinary assignments — no special-case
/// authorization logic" (build plan §3, TIM-FR-008/009, AC-022).
/// </summary>
public sealed class AssignmentRole
{
    public Guid Id { get; init; }

    public required string Code { get; init; }

    public required string Name { get; set; }

    public int DisplayOrder { get; set; }

    public bool IsActive { get; set; } = true;
}

public static class AssignmentRoleCodes
{
    public const string Ordinary = "ORDINARY";
    public const string Substitute = "SUBSTITUTE";
}
