// <auto-generated />
using System;
using HAMS.ReportingAnalyticsAudit.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HAMS.ReportingAnalyticsAudit.Migrations
{
    [DbContext(typeof(ReportingAnalyticsAuditDbContext))]
    [Migration("20260805092054_InitialReportingAnalyticsAudit")]
    partial class InitialReportingAnalyticsAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reporting")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HAMS.ReportingAnalyticsAudit.Domain.ReportCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("EvaluationPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("NarrativeDv")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("NarrativeEn")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("NextStepsDv")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("NextStepsEn")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("PreparedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PreparedByPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("StudentPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SupersededById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentPersonId", "EvaluationPeriodId", "IsCurrent");

                    b.ToTable("ReportCards", "reporting");
                });

            modelBuilder.Entity("HAMS.ReportingAnalyticsAudit.Domain.ReportCardKeyCompetencySummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AverageRatingScore")
                        .HasColumnType("float");

                    b.Property<int>("EvidenceCount")
                        .HasColumnType("int");

                    b.Property<Guid>("KeyCompetencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReportCardId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReportCardId");

                    b.ToTable("ReportCardKeyCompetencySummaries", "reporting");
                });

            modelBuilder.Entity("HAMS.ReportingAnalyticsAudit.Domain.ReportCardSubjectResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AchievementLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GradeBandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("ReportCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceKeyStageEvaluationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReportCardId");

                    b.ToTable("ReportCardSubjectResults", "reporting");
                });

            modelBuilder.Entity("HAMS.ReportingAnalyticsAudit.Domain.ReportCardKeyCompetencySummary", b =>
                {
                    b.HasOne("HAMS.ReportingAnalyticsAudit.Domain.ReportCard", null)
                        .WithMany()
                        .HasForeignKey("ReportCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.ReportingAnalyticsAudit.Domain.ReportCardSubjectResult", b =>
                {
                    b.HasOne("HAMS.ReportingAnalyticsAudit.Domain.ReportCard", null)
                        .WithMany()
                        .HasForeignKey("ReportCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
