using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace HAMS.ReportingAnalyticsAudit.Migrations
{
    /// <inheritdoc />
    /// <summary>
    /// Four read-only cross-schema SQL views (build plan §2's explicit exception granted to this
    /// module alone: "ReportingAnalyticsAudit gets read-only cross-schema SQL views for
    /// dashboards/regulatory reports — that's its entire job — but it never writes outside its own
    /// schema"). EF Core's migration generator doesn't emit DDL for keyless view-backed entities on
    /// its own, so this SQL is hand-written, not autogenerated — mapped back in
    /// <see cref="HAMS.ReportingAnalyticsAudit.Infrastructure.ReportingAnalyticsAuditDbContext"/> via
    /// <c>HasNoKey().ToView(...)</c>.
    /// </summary>
    public partial class DashboardAndExportViews : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                CREATE VIEW reporting.vw_StudentRoster AS
                SELECT
                    se.Id AS EnrollmentId,
                    se.StudentPersonId,
                    sp.AdmissionNumber,
                    p.NameEn AS StudentNameEn,
                    p.NameDv AS StudentNameDv,
                    se.AcademicYearId,
                    ay.Code AS AcademicYearCode,
                    ay.Name AS AcademicYearName,
                    se.GradeId,
                    g.Code AS GradeCode,
                    g.Name AS GradeName,
                    se.ClassId,
                    c.Code AS ClassCode,
                    c.Name AS ClassName,
                    se.EffectiveFrom,
                    se.EffectiveTo
                FROM people.StudentEnrollments se
                INNER JOIN people.StudentProfiles sp ON sp.PersonId = se.StudentPersonId
                INNER JOIN people.People p ON p.Id = se.StudentPersonId
                INNER JOIN org.AcademicYears ay ON ay.Id = se.AcademicYearId
                INNER JOIN org.Grades g ON g.Id = se.GradeId
                INNER JOIN org.Classes c ON c.Id = se.ClassId
                WHERE se.EffectiveFrom <= CAST(GETUTCDATE() AS DATE)
                  AND (se.EffectiveTo IS NULL OR se.EffectiveTo >= CAST(GETUTCDATE() AS DATE))
                """);

            migrationBuilder.Sql("""
                CREATE VIEW reporting.vw_AttendanceRecords AS
                SELECT
                    dar.Id AS RecordId,
                    dar.StudentPersonId,
                    p.NameEn AS StudentNameEn,
                    p.NameDv AS StudentNameDv,
                    dar.Date,
                    dar.AcademicYearId,
                    dar.AttendanceStatusId,
                    st.Code AS AttendanceStatusCode,
                    st.Name AS AttendanceStatusName
                FROM attendance.DailyAttendanceRecords dar
                INNER JOIN people.People p ON p.Id = dar.StudentPersonId
                INNER JOIN attendance.AttendanceStatuses st ON st.Id = dar.AttendanceStatusId
                """);

            migrationBuilder.Sql("""
                CREATE VIEW reporting.vw_InterventionCaseSummary AS
                SELECT
                    ic.AcademicYearId,
                    ic.InterventionTypeId,
                    it.Code AS InterventionTypeCode,
                    it.Name AS InterventionTypeName,
                    ic.Status,
                    COUNT(*) AS CaseCount
                FROM intervention.InterventionCases ic
                INNER JOIN intervention.InterventionTypes it ON it.Id = ic.InterventionTypeId
                GROUP BY ic.AcademicYearId, ic.InterventionTypeId, it.Code, it.Name, ic.Status
                """);

            migrationBuilder.Sql("""
                CREATE VIEW reporting.vw_PromotionDecisions AS
                SELECT
                    pd.Id AS DecisionId,
                    pd.StudentPersonId,
                    p.NameEn AS StudentNameEn,
                    p.NameDv AS StudentNameDv,
                    pd.AcademicYearId,
                    ay.Code AS AcademicYearCode,
                    pd.CurrentGradeId,
                    cg.Name AS CurrentGradeName,
                    pd.Promoted,
                    pd.NextGradeId,
                    ng.Name AS NextGradeName,
                    pd.DecisionDate,
                    pd.Notes,
                    pd.RecordedAtUtc
                FROM assessment.PromotionDecisions pd
                INNER JOIN people.People p ON p.Id = pd.StudentPersonId
                INNER JOIN org.AcademicYears ay ON ay.Id = pd.AcademicYearId
                INNER JOIN org.Grades cg ON cg.Id = pd.CurrentGradeId
                LEFT JOIN org.Grades ng ON ng.Id = pd.NextGradeId
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP VIEW reporting.vw_PromotionDecisions");
            migrationBuilder.Sql("DROP VIEW reporting.vw_InterventionCaseSummary");
            migrationBuilder.Sql("DROP VIEW reporting.vw_AttendanceRecords");
            migrationBuilder.Sql("DROP VIEW reporting.vw_StudentRoster");
        }
    }
}
