// <auto-generated />
using System;
using HAMS.ReportingAnalyticsAudit.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HAMS.ReportingAnalyticsAudit.Migrations
{
    [DbContext(typeof(ReportingAnalyticsAuditDbContext))]
    [Migration("20260805131300_DashboardAndExportViews")]
    partial class DashboardAndExportViews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reporting")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HAMS.ReportingAnalyticsAudit.Domain.ReportCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("EvaluationPeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("NarrativeDv")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("NarrativeEn")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("NextStepsDv")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("NextStepsEn")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("PreparedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PreparedByPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("StudentPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SupersededById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentPersonId", "EvaluationPeriodId", "IsCurrent");

                    b.ToTable("ReportCards", "reporting");
                });

            modelBuilder.Entity("HAMS.ReportingAnalyticsAudit.Domain.ReportCardKeyCompetencySummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("AverageRatingScore")
                        .HasColumnType("float");

                    b.Property<int>("EvidenceCount")
                        .HasColumnType("int");

                    b.Property<Guid>("KeyCompetencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReportCardId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReportCardId");

                    b.ToTable("ReportCardKeyCompetencySummaries", "reporting");
                });

            modelBuilder.Entity("HAMS.ReportingAnalyticsAudit.Domain.ReportCardSubjectResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AchievementLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GradeBandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Percentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("ReportCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceKeyStageEvaluationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReportCardId");

                    b.ToTable("ReportCardSubjectResults", "reporting");
                });

            modelBuilder.Entity("HAMS.ReportingAnalyticsAudit.Domain.Views.AttendanceRecordRow", b =>
                {
                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttendanceStatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AttendanceStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttendanceStatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StudentNameDv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable((string)null);

                    b.ToView("vw_AttendanceRecords", "reporting");
                });

            modelBuilder.Entity("HAMS.ReportingAnalyticsAudit.Domain.Views.InterventionCaseSummaryRow", b =>
                {
                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CaseCount")
                        .HasColumnType("int");

                    b.Property<string>("InterventionTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InterventionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InterventionTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView("vw_InterventionCaseSummary", "reporting");
                });

            modelBuilder.Entity("HAMS.ReportingAnalyticsAudit.Domain.Views.PromotionDecisionRow", b =>
                {
                    b.Property<string>("AcademicYearCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrentGradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CurrentGradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DecisionDate")
                        .HasColumnType("date");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NextGradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NextGradeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Promoted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StudentNameDv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable((string)null);

                    b.ToView("vw_PromotionDecisions", "reporting");
                });

            modelBuilder.Entity("HAMS.ReportingAnalyticsAudit.Domain.Views.StudentRosterRow", b =>
                {
                    b.Property<string>("AcademicYearCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AcademicYearName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdmissionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GradeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNameDv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentNameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.ToTable((string)null);

                    b.ToView("vw_StudentRoster", "reporting");
                });

            modelBuilder.Entity("HAMS.ReportingAnalyticsAudit.Domain.ReportCardKeyCompetencySummary", b =>
                {
                    b.HasOne("HAMS.ReportingAnalyticsAudit.Domain.ReportCard", null)
                        .WithMany()
                        .HasForeignKey("ReportCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.ReportingAnalyticsAudit.Domain.ReportCardSubjectResult", b =>
                {
                    b.HasOne("HAMS.ReportingAnalyticsAudit.Domain.ReportCard", null)
                        .WithMany()
                        .HasForeignKey("ReportCardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
