<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HAMS.Platform.Common\HAMS.Platform.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="HAMS.Platform.Workflow.Tests" />
    <InternalsVisibleTo Include="HAMS.AssessmentEvaluation.Tests" />
    <InternalsVisibleTo Include="HAMS.Intervention.Tests" />
    <InternalsVisibleTo Include="HAMS.ReportingAnalyticsAudit.Tests" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
