// <auto-generated />
using System;
using HAMS.CommunicationPortals.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HAMS.CommunicationPortals.Migrations
{
    [DbContext(typeof(CommunicationPortalsDbContext))]
    [Migration("20260805150910_InitialCommunicationPortals")]
    partial class InitialCommunicationPortals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("portals")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HAMS.CommunicationPortals.Domain.GuardianAcknowledgement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AcknowledgedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("GuardianPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GuardianPersonId", "StudentPersonId", "EntityType", "EntityId")
                        .IsUnique();

                    b.ToTable("GuardianAcknowledgements", "portals");
                });
#pragma warning restore 612, 618
        }
    }
}
