// <auto-generated />
using System;
using HAMS.Platform.Access.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HAMS.Platform.Access.Migrations
{
    [DbContext(typeof(AccessDbContext))]
    [Migration("20260804063343_InitialAccess")]
    partial class InitialAccess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("access")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HAMS.Platform.Access.Domain.AccessGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CampusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConfidentialityTierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid?>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KeyStageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConfidentialityTierId");

                    b.HasIndex("RoleId");

                    b.HasIndex("SourceType", "SourceId");

                    b.HasIndex("PersonId", "EffectiveFrom", "EffectiveTo");

                    b.ToTable("AccessGrants", "access");
                });

            modelBuilder.Entity("HAMS.Platform.Access.Domain.ConfidentialAccessGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConfidentialityTierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConfidentialityTierId");

                    b.HasIndex("PersonId", "StudentId", "EffectiveFrom", "EffectiveTo");

                    b.ToTable("ConfidentialAccessGrants", "access");
                });

            modelBuilder.Entity("HAMS.Platform.Access.Domain.ConfidentialityTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ConfidentialityTiers", "access");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000001"),
                            Code = "RESTRICTED",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Restricted",
                            Rank = 1
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0002-000000000002"),
                            Code = "SAFEGUARDING",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Safeguarding",
                            Rank = 2
                        });
                });

            modelBuilder.Entity("HAMS.Platform.Access.Domain.PersonRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("PersonId", "EffectiveFrom", "EffectiveTo");

                    b.ToTable("PersonRoleAssignments", "access");
                });

            modelBuilder.Entity("HAMS.Platform.Access.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Roles", "access");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000001"),
                            Code = "SYSTEM_ADMINISTRATOR",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "System Administrator"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000002"),
                            Code = "SCHOOL_ADMINISTRATOR",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "School Administrator"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000003"),
                            Code = "PRINCIPAL",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Principal"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000004"),
                            Code = "DEPUTY_PRINCIPAL",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Deputy Principal"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000005"),
                            Code = "CLASS_TEACHER",
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "Class Teacher"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000006"),
                            Code = "SUBJECT_TEACHER",
                            DisplayOrder = 6,
                            IsActive = true,
                            Name = "Subject Teacher"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000007"),
                            Code = "LEADING_TEACHER",
                            DisplayOrder = 7,
                            IsActive = true,
                            Name = "Leading Teacher"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000008"),
                            Code = "STUDENT",
                            DisplayOrder = 8,
                            IsActive = true,
                            Name = "Student"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000009"),
                            Code = "GUARDIAN",
                            DisplayOrder = 9,
                            IsActive = true,
                            Name = "Guardian"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000010"),
                            Code = "REGULATORY_OFFICER",
                            DisplayOrder = 10,
                            IsActive = true,
                            Name = "Regulatory Officer"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000011"),
                            Code = "SCHOOL_INSPECTOR",
                            DisplayOrder = 11,
                            IsActive = true,
                            Name = "School Inspector"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0001-000000000012"),
                            Code = "AUDITOR",
                            DisplayOrder = 12,
                            IsActive = true,
                            Name = "Auditor"
                        });
                });

            modelBuilder.Entity("HAMS.Platform.Access.Domain.AccessGrant", b =>
                {
                    b.HasOne("HAMS.Platform.Access.Domain.ConfidentialityTier", null)
                        .WithMany()
                        .HasForeignKey("ConfidentialityTierId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HAMS.Platform.Access.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.Platform.Access.Domain.ConfidentialAccessGrant", b =>
                {
                    b.HasOne("HAMS.Platform.Access.Domain.ConfidentialityTier", null)
                        .WithMany()
                        .HasForeignKey("ConfidentialityTierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.Platform.Access.Domain.PersonRoleAssignment", b =>
                {
                    b.HasOne("HAMS.Platform.Access.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
