// <auto-generated />
using System;
using HAMS.LearningDelivery.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HAMS.LearningDelivery.Migrations
{
    [DbContext(typeof(LearningDeliveryDbContext))]
    [Migration("20260805144835_HomeworkAssignments")]
    partial class HomeworkAssignments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("learning")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.AchievementLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AchievementScaleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AchievementScaleId", "Code")
                        .IsUnique();

                    b.ToTable("AchievementLevels", "learning");
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.AchievementScale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MinimumEvidenceCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AchievementScales", "learning");
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.EvidenceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("EvidenceTypes", "learning");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0018-000000000001"),
                            Code = "OBSERVATION",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Observation"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0018-000000000002"),
                            Code = "WORK_SAMPLE",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Work Sample"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0018-000000000003"),
                            Code = "QUIZ",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Quiz"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0018-000000000004"),
                            Code = "ANECDOTAL_NOTE",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Anecdotal Note"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0018-000000000005"),
                            Code = "RATING_SCALE",
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "Rating Scale"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0018-000000000006"),
                            Code = "CHECKLIST",
                            DisplayOrder = 6,
                            IsActive = true,
                            Name = "Checklist"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0018-000000000007"),
                            Code = "PORTFOLIO_REFERENCE",
                            DisplayOrder = 7,
                            IsActive = true,
                            Name = "Portfolio Reference"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0018-000000000008"),
                            Code = "OTHER",
                            DisplayOrder = 8,
                            IsActive = true,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.Homework", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignedByPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("AssignedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("InstructionsDv")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("InstructionsEn")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("MaxScore")
                        .HasColumnType("int");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TeachingTopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TitleDv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("TeachingTopicId");

                    b.HasIndex("ClassId", "DueDate");

                    b.ToTable("Homeworks", "learning");
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.HomeworkSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FeedbackText")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FileReference")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("GradedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("GradedByPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HomeworkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubmissionText")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset>("SubmittedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("HomeworkId", "StudentPersonId")
                        .IsUnique();

                    b.ToTable("HomeworkSubmissions", "learning");
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.KeyCompetency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("NameDv")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("KeyCompetencies", "learning");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0019-000000000001"),
                            Code = "PRACTISING_ISLAM",
                            DisplayOrder = 1,
                            NameEn = "Practising Islam"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0019-000000000002"),
                            Code = "UNDERSTANDING_MANAGING_SELF",
                            DisplayOrder = 2,
                            NameEn = "Understanding & Managing Self"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0019-000000000003"),
                            Code = "THINKING_CRITICALLY_CREATIVELY",
                            DisplayOrder = 3,
                            NameEn = "Thinking Critically & Creatively"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0019-000000000004"),
                            Code = "RELATING_TO_PEOPLE",
                            DisplayOrder = 4,
                            NameEn = "Relating to People"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0019-000000000005"),
                            Code = "MAKING_MEANING",
                            DisplayOrder = 5,
                            NameEn = "Making Meaning"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0019-000000000006"),
                            Code = "LIVING_HEALTHY_LIFE",
                            DisplayOrder = 6,
                            NameEn = "Living a Healthy Life"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0019-000000000007"),
                            Code = "USING_SUSTAINABLE_PRACTICES",
                            DisplayOrder = 7,
                            NameEn = "Using Sustainable Practices"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0019-000000000008"),
                            Code = "USING_TECHNOLOGY_MEDIA",
                            DisplayOrder = 8,
                            NameEn = "Using Technology & the Media"
                        });
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.KeyCompetencyEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvidenceTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KeyCompetencyIndicatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("RatingScore")
                        .HasColumnType("int");

                    b.Property<Guid>("RecordedByPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("RecordedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("StudentPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceTypeId");

                    b.HasIndex("KeyCompetencyIndicatorId");

                    b.HasIndex("StudentPersonId", "KeyCompetencyIndicatorId");

                    b.ToTable("KeyCompetencyEvidences", "learning");
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.KeyCompetencyIndicator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DescriptionDv")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("KeyCompetencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KeyStageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("KeyCompetencyId", "KeyStageId");

                    b.ToTable("KeyCompetencyIndicators", "learning");
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.LearningEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AchievementLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvidenceTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LearningOutcomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LessonSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("RecordedByPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("RecordedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("StudentPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AchievementLevelId");

                    b.HasIndex("EvidenceTypeId");

                    b.HasIndex("LessonSessionId");

                    b.HasIndex("StudentPersonId", "LearningOutcomeId");

                    b.ToTable("LearningEvidences", "learning");
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.LessonPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Objectives")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateOnly>("PlannedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("StaffPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeachingTopicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StaffPersonId");

                    b.HasIndex("TeachingTopicId");

                    b.ToTable("LessonPlans", "learning");
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.LessonSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ActualDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LessonPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("LessonPlanId");

                    b.HasIndex("ClassId", "ActualDate", "PeriodId");

                    b.ToTable("LessonSessions", "learning");
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.LessonSessionOutcomeCoverage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LearningOutcomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LessonSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LessonSessionId", "LearningOutcomeId")
                        .IsUnique();

                    b.ToTable("LessonSessionOutcomeCoverages", "learning");
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.MasteryEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AchievementLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AchievementScaleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EvidenceCountAtEvaluation")
                        .HasColumnType("int");

                    b.Property<Guid>("KeyStagePolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LearningOutcomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RecordedByPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("WasManuallyOverridden")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AchievementLevelId");

                    b.HasIndex("AchievementScaleId");

                    b.HasIndex("StudentPersonId", "LearningOutcomeId", "RecordedAtUtc");

                    b.ToTable("MasteryEvaluations", "learning");
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileReference")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ResourceTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeachingTopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TitleDv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UploadedByPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResourceTypeId");

                    b.HasIndex("TeachingTopicId");

                    b.ToTable("Resources", "learning");
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.ResourceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ResourceTypes", "learning");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0016-000000000001"),
                            Code = "DOCUMENT",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Document"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0016-000000000002"),
                            Code = "VIDEO",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Video"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0016-000000000003"),
                            Code = "LINK",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Link"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0016-000000000004"),
                            Code = "OTHER",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.SchemeOfWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "GradeId", "AcademicYearId")
                        .IsUnique();

                    b.ToTable("SchemeOfWorks", "learning");
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.SchemeOfWorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("LearningOutcomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlannedWeekNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("SchemeOfWorkId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LearningOutcomeId");

                    b.HasIndex("SchemeOfWorkId");

                    b.ToTable("SchemeOfWorkItems", "learning");
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.TeachingTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("NameDv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SchemeOfWorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SchemeOfWorkItemId");

                    b.ToTable("TeachingTopics", "learning");
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.AchievementLevel", b =>
                {
                    b.HasOne("HAMS.LearningDelivery.Domain.AchievementScale", null)
                        .WithMany()
                        .HasForeignKey("AchievementScaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.Homework", b =>
                {
                    b.HasOne("HAMS.LearningDelivery.Domain.TeachingTopic", null)
                        .WithMany()
                        .HasForeignKey("TeachingTopicId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.HomeworkSubmission", b =>
                {
                    b.HasOne("HAMS.LearningDelivery.Domain.Homework", null)
                        .WithMany()
                        .HasForeignKey("HomeworkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.KeyCompetencyEvidence", b =>
                {
                    b.HasOne("HAMS.LearningDelivery.Domain.EvidenceType", null)
                        .WithMany()
                        .HasForeignKey("EvidenceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.LearningDelivery.Domain.KeyCompetencyIndicator", null)
                        .WithMany()
                        .HasForeignKey("KeyCompetencyIndicatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.KeyCompetencyIndicator", b =>
                {
                    b.HasOne("HAMS.LearningDelivery.Domain.KeyCompetency", null)
                        .WithMany()
                        .HasForeignKey("KeyCompetencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.LearningEvidence", b =>
                {
                    b.HasOne("HAMS.LearningDelivery.Domain.AchievementLevel", null)
                        .WithMany()
                        .HasForeignKey("AchievementLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.LearningDelivery.Domain.EvidenceType", null)
                        .WithMany()
                        .HasForeignKey("EvidenceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.LearningDelivery.Domain.LessonSession", null)
                        .WithMany()
                        .HasForeignKey("LessonSessionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.LessonPlan", b =>
                {
                    b.HasOne("HAMS.LearningDelivery.Domain.TeachingTopic", null)
                        .WithMany()
                        .HasForeignKey("TeachingTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.LessonSession", b =>
                {
                    b.HasOne("HAMS.LearningDelivery.Domain.LessonPlan", null)
                        .WithMany()
                        .HasForeignKey("LessonPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.LessonSessionOutcomeCoverage", b =>
                {
                    b.HasOne("HAMS.LearningDelivery.Domain.LessonSession", null)
                        .WithMany()
                        .HasForeignKey("LessonSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.MasteryEvaluation", b =>
                {
                    b.HasOne("HAMS.LearningDelivery.Domain.AchievementLevel", null)
                        .WithMany()
                        .HasForeignKey("AchievementLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.LearningDelivery.Domain.AchievementScale", null)
                        .WithMany()
                        .HasForeignKey("AchievementScaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.Resource", b =>
                {
                    b.HasOne("HAMS.LearningDelivery.Domain.ResourceType", null)
                        .WithMany()
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.LearningDelivery.Domain.TeachingTopic", null)
                        .WithMany()
                        .HasForeignKey("TeachingTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.SchemeOfWorkItem", b =>
                {
                    b.HasOne("HAMS.LearningDelivery.Domain.SchemeOfWork", null)
                        .WithMany()
                        .HasForeignKey("SchemeOfWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.TeachingTopic", b =>
                {
                    b.HasOne("HAMS.LearningDelivery.Domain.SchemeOfWorkItem", null)
                        .WithMany()
                        .HasForeignKey("SchemeOfWorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
