// <auto-generated />
using System;
using HAMS.LearningDelivery.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HAMS.LearningDelivery.Migrations
{
    [DbContext(typeof(LearningDeliveryDbContext))]
    [Migration("20260804103424_InitialLearningDelivery")]
    partial class InitialLearningDelivery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("learning")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.LessonPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Objectives")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateOnly>("PlannedDate")
                        .HasColumnType("date");

                    b.Property<Guid>("StaffPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeachingTopicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StaffPersonId");

                    b.HasIndex("TeachingTopicId");

                    b.ToTable("LessonPlans", "learning");
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.LessonSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ActualDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LessonPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("LessonPlanId");

                    b.HasIndex("ClassId", "ActualDate", "PeriodId");

                    b.ToTable("LessonSessions", "learning");
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.LessonSessionOutcomeCoverage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LearningOutcomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LessonSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LessonSessionId", "LearningOutcomeId")
                        .IsUnique();

                    b.ToTable("LessonSessionOutcomeCoverages", "learning");
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileReference")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ResourceTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeachingTopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TitleDv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UploadedByPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ResourceTypeId");

                    b.HasIndex("TeachingTopicId");

                    b.ToTable("Resources", "learning");
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.ResourceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ResourceTypes", "learning");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0016-000000000001"),
                            Code = "DOCUMENT",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Document"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0016-000000000002"),
                            Code = "VIDEO",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Video"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0016-000000000003"),
                            Code = "LINK",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Link"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0016-000000000004"),
                            Code = "OTHER",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.SchemeOfWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId", "GradeId", "AcademicYearId")
                        .IsUnique();

                    b.ToTable("SchemeOfWorks", "learning");
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.SchemeOfWorkItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("LearningOutcomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PlannedWeekNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("SchemeOfWorkId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LearningOutcomeId");

                    b.HasIndex("SchemeOfWorkId");

                    b.ToTable("SchemeOfWorkItems", "learning");
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.TeachingTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("NameDv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SchemeOfWorkItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SchemeOfWorkItemId");

                    b.ToTable("TeachingTopics", "learning");
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.LessonPlan", b =>
                {
                    b.HasOne("HAMS.LearningDelivery.Domain.TeachingTopic", null)
                        .WithMany()
                        .HasForeignKey("TeachingTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.LessonSession", b =>
                {
                    b.HasOne("HAMS.LearningDelivery.Domain.LessonPlan", null)
                        .WithMany()
                        .HasForeignKey("LessonPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.LessonSessionOutcomeCoverage", b =>
                {
                    b.HasOne("HAMS.LearningDelivery.Domain.LessonSession", null)
                        .WithMany()
                        .HasForeignKey("LessonSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.Resource", b =>
                {
                    b.HasOne("HAMS.LearningDelivery.Domain.ResourceType", null)
                        .WithMany()
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.LearningDelivery.Domain.TeachingTopic", null)
                        .WithMany()
                        .HasForeignKey("TeachingTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.SchemeOfWorkItem", b =>
                {
                    b.HasOne("HAMS.LearningDelivery.Domain.SchemeOfWork", null)
                        .WithMany()
                        .HasForeignKey("SchemeOfWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.LearningDelivery.Domain.TeachingTopic", b =>
                {
                    b.HasOne("HAMS.LearningDelivery.Domain.SchemeOfWorkItem", null)
                        .WithMany()
                        .HasForeignKey("SchemeOfWorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
