// <auto-generated />
using System;
using HAMS.PeopleEnrollment.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HAMS.PeopleEnrollment.Migrations
{
    [DbContext(typeof(PeopleDbContext))]
    partial class PeopleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("people")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HAMS.PeopleEnrollment.Domain.Atoll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NameDv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Atolls", "people");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000001"),
                            Code = "HA",
                            DisplayOrder = 1,
                            IsActive = true,
                            NameEn = "Haa Alifu"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000002"),
                            Code = "HDh",
                            DisplayOrder = 2,
                            IsActive = true,
                            NameEn = "Haa Dhaalu"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000003"),
                            Code = "Sh",
                            DisplayOrder = 3,
                            IsActive = true,
                            NameEn = "Shaviyani"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000004"),
                            Code = "N",
                            DisplayOrder = 4,
                            IsActive = true,
                            NameEn = "Noonu"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000005"),
                            Code = "R",
                            DisplayOrder = 5,
                            IsActive = true,
                            NameEn = "Raa"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000006"),
                            Code = "B",
                            DisplayOrder = 6,
                            IsActive = true,
                            NameEn = "Baa"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000007"),
                            Code = "Lh",
                            DisplayOrder = 7,
                            IsActive = true,
                            NameEn = "Lhaviyani"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000008"),
                            Code = "K",
                            DisplayOrder = 8,
                            IsActive = true,
                            NameEn = "Kaafu"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000009"),
                            Code = "AA",
                            DisplayOrder = 9,
                            IsActive = true,
                            NameEn = "Alifu Alifu"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000010"),
                            Code = "ADh",
                            DisplayOrder = 10,
                            IsActive = true,
                            NameEn = "Alifu Dhaalu"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000011"),
                            Code = "V",
                            DisplayOrder = 11,
                            IsActive = true,
                            NameEn = "Vaavu"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000012"),
                            Code = "M",
                            DisplayOrder = 12,
                            IsActive = true,
                            NameEn = "Meemu"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000013"),
                            Code = "F",
                            DisplayOrder = 13,
                            IsActive = true,
                            NameEn = "Faafu"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000014"),
                            Code = "Dh",
                            DisplayOrder = 14,
                            IsActive = true,
                            NameEn = "Dhaalu"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000015"),
                            Code = "Th",
                            DisplayOrder = 15,
                            IsActive = true,
                            NameEn = "Thaa"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000016"),
                            Code = "L",
                            DisplayOrder = 16,
                            IsActive = true,
                            NameEn = "Laamu"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000017"),
                            Code = "GA",
                            DisplayOrder = 17,
                            IsActive = true,
                            NameEn = "Gaafu Alifu"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000018"),
                            Code = "GDh",
                            DisplayOrder = 18,
                            IsActive = true,
                            NameEn = "Gaafu Dhaalu"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000019"),
                            Code = "Gn",
                            DisplayOrder = 19,
                            IsActive = true,
                            NameEn = "Gnaviyani"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0008-000000000020"),
                            Code = "S",
                            DisplayOrder = 20,
                            IsActive = true,
                            NameEn = "Seenu"
                        });
                });

            modelBuilder.Entity("HAMS.PeopleEnrollment.Domain.EmploymentStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("EmploymentStatuses", "people");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0010-000000000001"),
                            Code = "ACTIVE",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Active"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0010-000000000002"),
                            Code = "ON_LEAVE",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "On Leave"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0010-000000000003"),
                            Code = "RESIGNED",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Resigned"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0010-000000000004"),
                            Code = "RETIRED",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Retired"
                        });
                });

            modelBuilder.Entity("HAMS.PeopleEnrollment.Domain.EnrollmentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("EnrollmentTypes", "people");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0012-000000000001"),
                            Code = "ORDINARY",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Ordinary"
                        });
                });

            modelBuilder.Entity("HAMS.PeopleEnrollment.Domain.GuardianProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("GuardianProfiles", "people");
                });

            modelBuilder.Entity("HAMS.PeopleEnrollment.Domain.GuardianStudentRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CanReceiveNotifications")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewAcademicRecords")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewAttendance")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewBehaviourRecords")
                        .HasColumnType("bit");

                    b.Property<bool>("CanViewInterventionUpdates")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid>("GuardianPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasLegalAuthority")
                        .HasColumnType("bit");

                    b.Property<Guid>("RelationshipTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RestrictionTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("RelationshipTypeId");

                    b.HasIndex("RestrictionTypeId");

                    b.HasIndex("StudentPersonId");

                    b.HasIndex("GuardianPersonId", "StudentPersonId", "EffectiveFrom", "EffectiveTo");

                    b.ToTable("GuardianStudentRelationships", "people");
                });

            modelBuilder.Entity("HAMS.PeopleEnrollment.Domain.Island", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtollId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NameDv")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AtollId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Islands", "people");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0009-000000000001"),
                            AtollId = new Guid("00000000-0000-0000-0008-000000000015"),
                            Code = "HIRILANDHOO",
                            DisplayOrder = 1,
                            IsActive = true,
                            NameEn = "Hirilandhoo"
                        });
                });

            modelBuilder.Entity("HAMS.PeopleEnrollment.Domain.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NameDv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("People", "people");
                });

            modelBuilder.Entity("HAMS.PeopleEnrollment.Domain.RelationshipType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RelationshipTypes", "people");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0011-000000000001"),
                            Code = "MOTHER",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Mother"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0011-000000000002"),
                            Code = "FATHER",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Father"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0011-000000000003"),
                            Code = "GRANDPARENT",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Grandparent"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0011-000000000004"),
                            Code = "LEGAL_GUARDIAN",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Legal Guardian"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0011-000000000005"),
                            Code = "OTHER",
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("HAMS.PeopleEnrollment.Domain.RestrictionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("RestrictionTypes", "people");
                });

            modelBuilder.Entity("HAMS.PeopleEnrollment.Domain.StaffProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("EmploymentStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.HasIndex("EmploymentStatusId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("StaffProfiles", "people");
                });

            modelBuilder.Entity("HAMS.PeopleEnrollment.Domain.StaffQualification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AwardingInstitution")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("StaffProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("YearAwarded")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StaffProfileId");

                    b.ToTable("StaffQualifications", "people");
                });

            modelBuilder.Entity("HAMS.PeopleEnrollment.Domain.StudentEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<Guid>("EnrollmentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EnrollmentTypeId");

                    b.HasIndex("StudentPersonId", "AcademicYearId")
                        .IsUnique()
                        .HasDatabaseName("IX_StudentEnrollments_OneActiveOrdinaryPerStudentYear")
                        .HasFilter("[EnrollmentTypeId] = '00000000-0000-0000-0012-000000000001' AND [EffectiveTo] IS NULL");

                    b.HasIndex("StudentPersonId", "AcademicYearId", "EffectiveFrom", "EffectiveTo");

                    b.ToTable("StudentEnrollments", "people");
                });

            modelBuilder.Entity("HAMS.PeopleEnrollment.Domain.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("AdmissionDate")
                        .HasColumnType("date");

                    b.Property<string>("AdmissionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionNumber")
                        .IsUnique();

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.ToTable("StudentProfiles", "people");
                });

            modelBuilder.Entity("HAMS.PeopleEnrollment.Domain.GuardianProfile", b =>
                {
                    b.HasOne("HAMS.PeopleEnrollment.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.PeopleEnrollment.Domain.GuardianStudentRelationship", b =>
                {
                    b.HasOne("HAMS.PeopleEnrollment.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("GuardianPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.PeopleEnrollment.Domain.RelationshipType", null)
                        .WithMany()
                        .HasForeignKey("RelationshipTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.PeopleEnrollment.Domain.RestrictionType", null)
                        .WithMany()
                        .HasForeignKey("RestrictionTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HAMS.PeopleEnrollment.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("StudentPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.PeopleEnrollment.Domain.Island", b =>
                {
                    b.HasOne("HAMS.PeopleEnrollment.Domain.Atoll", null)
                        .WithMany()
                        .HasForeignKey("AtollId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.PeopleEnrollment.Domain.Person", b =>
                {
                    b.OwnsOne("HAMS.PeopleEnrollment.Domain.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("PersonId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Apartment")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Address_Apartment");

                            b1.Property<string>("BuildingDv")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Address_BuildingDv");

                            b1.Property<string>("BuildingEn")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Address_BuildingEn");

                            b1.Property<string>("Floor")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Address_Floor");

                            b1.Property<string>("HouseNameDv")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Address_HouseNameDv");

                            b1.Property<string>("HouseNameEn")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Address_HouseNameEn");

                            b1.Property<Guid>("IslandId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("Address_IslandId");

                            b1.Property<string>("RoadDv")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Address_RoadDv");

                            b1.Property<string>("RoadEn")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Address_RoadEn");

                            b1.HasKey("PersonId");

                            b1.HasIndex("IslandId");

                            b1.ToTable("People", "people");

                            b1.HasOne("HAMS.PeopleEnrollment.Domain.Island", null)
                                .WithMany()
                                .HasForeignKey("IslandId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("PersonId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.PeopleEnrollment.Domain.StaffProfile", b =>
                {
                    b.HasOne("HAMS.PeopleEnrollment.Domain.EmploymentStatus", null)
                        .WithMany()
                        .HasForeignKey("EmploymentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HAMS.PeopleEnrollment.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.PeopleEnrollment.Domain.StaffQualification", b =>
                {
                    b.HasOne("HAMS.PeopleEnrollment.Domain.StaffProfile", null)
                        .WithMany()
                        .HasForeignKey("StaffProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.PeopleEnrollment.Domain.StudentEnrollment", b =>
                {
                    b.HasOne("HAMS.PeopleEnrollment.Domain.EnrollmentType", null)
                        .WithMany()
                        .HasForeignKey("EnrollmentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.PeopleEnrollment.Domain.StudentProfile", b =>
                {
                    b.HasOne("HAMS.PeopleEnrollment.Domain.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
