// <auto-generated />
using System;
using HAMS.Attendance.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HAMS.Attendance.Migrations
{
    [DbContext(typeof(AttendanceDbContext))]
    partial class AttendanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("attendance")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HAMS.Attendance.Domain.AttendanceStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("AttendanceStatuses", "attendance");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0015-000000000001"),
                            Code = "PRESENT",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Present"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0015-000000000002"),
                            Code = "ABSENT",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Absent"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0015-000000000003"),
                            Code = "LATE",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Late"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0015-000000000004"),
                            Code = "EXCUSED",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Excused"
                        });
                });

            modelBuilder.Entity("HAMS.Attendance.Domain.DailyAttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcademicYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttendanceStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("RecordedByPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceStatusId");

                    b.HasIndex("StudentPersonId", "Date")
                        .IsUnique();

                    b.ToTable("DailyAttendanceRecords", "attendance");
                });

            modelBuilder.Entity("HAMS.Attendance.Domain.LessonAttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttendanceStatusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LessonSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("RecordedByPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentPersonId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceStatusId");

                    b.HasIndex("StudentPersonId", "LessonSessionId")
                        .IsUnique();

                    b.ToTable("LessonAttendanceRecords", "attendance");
                });

            modelBuilder.Entity("HAMS.Attendance.Domain.DailyAttendanceRecord", b =>
                {
                    b.HasOne("HAMS.Attendance.Domain.AttendanceStatus", null)
                        .WithMany()
                        .HasForeignKey("AttendanceStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("HAMS.Attendance.Domain.LessonAttendanceRecord", b =>
                {
                    b.HasOne("HAMS.Attendance.Domain.AttendanceStatus", null)
                        .WithMany()
                        .HasForeignKey("AttendanceStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
